permalink: /:year/:month/:day/:title.html
paginate: 15
markdown: redcarpet

# 作者信息
author: 
  name: 潘凯 
  email: pankkk@hotmail.com
  link: http://rockypan.github.io
  github: http://github.com/RockyPan

# 站点信息
title: 潘凯的博客 
description: 潘凯的博客
url: http://rockypan.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: https://raw.githubusercontent.com/RockyPan/rockypan.github.com/master/asset/gavatar.png
favicon: https://raw.githubusercontent.com/RockyPan/rockypan.github.com/master/asset/favicon.ico

# google analytics 设置
# ga:
#   id: UA-54767140-1
#   url: yansu.org

# disqus 设置
disqus:
  shortname: rockypan

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Ada

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
